<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJoyedvz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJoyedvz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJoyedvz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJoyedvz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJoyedvz\appProdProjectContainer([
    'container.build_hash' => 'Joyedvz',
    'container.build_id' => '6850dd00',
    'container.build_time' => 1668599783,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJoyedvz');
