<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3qifqac\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3qifqac/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3qifqac.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3qifqac\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container3qifqac\appDevDebugProjectContainer([
    'container.build_hash' => '3qifqac',
    'container.build_id' => '25a3fd7d',
    'container.build_time' => 1647735175,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3qifqac');
